### ISSUE TITLE
Burp "Oracle Forms" tab always empty

### ISSUE THREAD

**Issue by xtsop** [v-p-b/oracle_forms#7]
The tool has helped me a lot with Oracle Forms testing but I would still like to see a fully decoded body of the request and response bodies. I cloned the project and build it on eclipse, then imported the created jar file to burp Extender with the output message being "Oracle Forms Serializer loaded" and no errors which looks ok. The Oracle Forms tab appears in the Proxy tab after that, but whenever I see a request or a response in the HTTP history, the Oracle Forms tab is completely empty.

Is there any chance the issue lies in how I built the extension? Do you have any pre-built jar files to use instead? Have you had the same issue before? I don't think the issue is the burp version.

Other than that everything works like a charm.

Thanks

**Comment by v-p-b** [comment]
Do you see any exceptions after you check one of the OracleForms tabs? I suggest you to test with a request that surely contains some parameters (e.g. recognizable character strings).

**Comment by xtsop** [comment]
Thanks for the response. No errors at all and I do have requests with numerous parameters. Is there any chance you also upload the jar files as well? I  only have some warning (no errors) regarding non-used imports etc.

**Comment by v-p-b** [comment]
I don't think your problem is related to your build, but to this particular line, that clears the tab if no content could be deserialized:

https://github.com/v-p-b/oracle_forms/blob/master/OracleFormsSerializer/src/burp/BurpExtender.java#L135

So I guess deserialization is failing. I'll need some time to familiarize myself with this code again, but this won't happen before the end of this week (possibly later) :(

In the meantime can you give the test applications at https://forms-demo.com/ a spin to see if the tab works with any of those apps?

**Comment by xtsop** [comment]
I checked against the first two sample apps and I have the same problem. If you can upload the pre-build jar, I will give it a try and if it still doesn't work I will exclude it from the potential reasons .

PS: a friend of mine has the same problem.

**Comment by v-p-b** [comment]
I just tested the code with forms-demo.com and it works as expected: 

![screen1554453596](https://user-images.githubusercontent.com/540246/55616376-fb546f80-5791-11e9-968f-d4f8845e8a7d.png)

Unfortunately I won't be able to distribute JARs as they would contain Oracle code (from frmall.jar). I used a simple Ant build to create my .JAR.

**Comment by gabyavra** [comment]
Hello,

Can you share the jar Burp extension?

**Comment by gabyavra** [comment]
Does it work with Burp 2.X ?

**Comment by ratzrattillo** [comment]
I am experiencing the same problems as @xtsop .
I am using BurpSuite Professional 2020.2.1 and i downloaded the code from Github for the OracleFormsSerializer.
It seems like the Mitmproxy script is doing a good job, as the encryption is terminated before reaching BurpSuite, as can be seen on the following screenshot, that i took after using the sample application at https://forms-demo.com/forms/frmservlet?config=DEMO0001:

![Decryption working well](https://user-images.githubusercontent.com/11601995/78672282-ba30f700-78e0-11ea-9944-94a904dade81.png)

However, the OracleForms-Tab stays empty aswell:

![Forms-Tab empty](https://user-images.githubusercontent.com/11601995/78672400-dfbe0080-78e0-11ea-9c49-c2a0daf231a4.png)

However, the Error-Tab in the Extender shows the following Stacktrace:
`	at burp.exj.lambda$new$0(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:418)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:269)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:622)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:597)
	at burp.exs.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4090)
	at java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at burp.exs.a(Unknown Source)
	at burp.exs.a(Unknown Source)
	at burp.d0q.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.RuntimeException: java.lang.NoClassDefFoundError: oracle/forms/engine/Message
	at burp.gsd.a(Unknown Source)
	at burp.dbg.a(Unknown Source)
	at burp.exj.a(Unknown Source)
	at burp.exj.e(Unknown Source)
	at burp.exj.lambda$new$0(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:418)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:269)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:622)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:597)
	at burp.exs.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4090)
	at java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at burp.exs.a(Unknown Source)
	at burp.exs.a(Unknown Source)
	at burp.d0q.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`



**Interesting is maybe the following Message:**

`java.lang.NoClassDefFoundError: oracle/forms/engine/Message`

**Comment by v-p-b** [comment]
@ratzrattillo You are righ that is the interesting part of the stack trace - the Message implementation is missing from your JAR - did you forget to include frmall.jar in the build?

**Comment by v-p-b** [comment]
Closing this as the title is too generic, and people are posting random stuff here. 

Seriously people, learn how to report bugs!
